version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: madlendb
    ports:
      - "5432:5432"
    networks:
      - app-network

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/madlendb?schema=public
    depends_on:
      - postgres
    networks:
      - app-network
    command: >
      sh -c "
        until nc -z -v -w30 postgres 5432; do
          echo 'Waiting for database connection...';
          sleep 1;
        done;
        npx prisma migrate deploy && npm run start
      "

networks:
  app-network:
    driver: bridge
